### ISSUE TITLE
Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by 111ar10** [i8beef/node-red-contrib-animate-gif#5]
Hi,

As mentioned in the other ticket I am getting this error.
It is not completely clear what is the node expecting...

More details below...

Looking at the flow below:

![image](https://user-images.githubusercontent.com/51876074/105149153-863b6100-5b03-11eb-940f-5b1e1c252d4c.png)

We can see that I am requesting a .jpg via HTTP node and the output is (step 0) - jpg 704x480.
The output of the HTTP node (step 1) is binary buffer:

![image](https://user-images.githubusercontent.com/51876074/105149471-db777280-5b03-11eb-878e-ea709b456b29.png)

In make array node I am combining outputted buffers into an array (step  2):

![image](https://user-images.githubusercontent.com/51876074/105149719-24c7c200-5b04-11eb-831d-b49b96a7b56c.png)

-> for the purpose of testing I am combining only 2 buffers for now

Finally in step 3 we can see that **animate-gif** node is outputting an error:
Input buffer contains unsupported image format

![image](https://user-images.githubusercontent.com/51876074/105149937-67899a00-5b04-11eb-9243-34a4368ab55f.png)

Animate-gif node is receiving an array consisting of 2 binary buffers (images) which are JPGs (704x480).
What might be the issue here? Because of not enough information on the node itself I am unaware if I am giving it an unexpected information on the input.

**Comment by i8beef** [comment]
The error is coming out of the underlying "sharp" library. I think your setup looks ok, so I would start by looking at the images you are using.

1. Where are you getting them / any chance they are not normal in some way?
2. Have you tried using images sourced from somewhere else that are known good?
3. Have you tried using gifs, or pngs instead?
4. What platform are you running on? sharp has some native dependencies, so one possibility is that you're missing its native package dependency (I've never had that issue, but there's some hints on their github page that different platforms might have issues)

I'd probably try the low hanging fruit first of trying some different images to test first, and see if you can narrow it down to just JPGs. I'd also make sure that the endpoint you are grabbing these from is actually providing an image (It LOOKS like it with the Image info node you have there, but as we don't have a great error to go on, making sure the resulting buffer is actually readable by ANOTHER node like node-red-contrib-image-output could at least help eliminate the source images themselves being the issue).

**Comment by 111ar10** [comment]
Hi Michael,

Thank you for very detailed response.
Don't know if the images might be malformed (they are fetched via API from camera and normally shown in the browser), but I will try to check your suggested tests.

I have added the node you mention (actually already had it installed) and the picture(s) are shown.
Will try other images and, since I am using node red in docker, will look into dependencies you mention.
Thanks a lot!

**Comment by cfullelove** [comment]
Hi

I had this issue too. Turns out that is was the package dependency issue as @i8beef suggested. The sharp library uses libvips, which isn't included in the standard node-red docker alpine based image.

To get this running, I added the package in the current container `apk add vips-dev`, restarted the container and everything worked :)

Obviously, this won't work if you rebuild the container for some reason (e.g. docker-compose or upgrading node-red). A longer-term fix would be to build your own image that includes the `vips-dev` package.

**Comment by 111ar10** [comment]
> Hi
> 
> I had this issue too. Turns out that is was the package dependency issue as @i8beef suggested. The sharp library uses libvips, which isn't included in the standard node-red docker alpine based image.
> 
> To get this running, I added the package in the current container `apk add vips-dev`, restarted the container and everything worked :)
> 
> Obviously, this won't work if you rebuild the container for some reason (e.g. docker-compose or upgrading node-red). A longer-term fix would be to build your own image that includes the `vips-dev` package.

Hey,

indeed it seems like a dependency issue.
I tried with several other images and got the same error.

After that uninstalled and reinstalled node:
-----------------------------------------------------------
2021-01-21T13:18:03.299Z Install : node-red-contrib-animate-gif 1.0.9

2021-01-21T13:18:03.888Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-animate-gif@1.0.9
2021-01-21T13:18:18.334Z [out] 
2021-01-21T13:18:18.334Z [out] > sharp@0.23.4 install /data/node_modules/node-red-contrib-animate-gif/node_modules/sharp
2021-01-21T13:18:18.334Z [out] > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
2021-01-21T13:18:18.334Z [out] 
2021-01-21T13:18:18.618Z [err] info
2021-01-21T13:18:18.619Z [err]  
2021-01-21T13:18:18.619Z [err] sharp
2021-01-21T13:18:18.619Z [err]  Using cached /data/.npm/_libvips/libvips-8.8.1-linuxmusl-x64.tar.gz
2021-01-21T13:18:21.880Z [err] npm
2021-01-21T13:18:21.880Z [err]  WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
2021-01-21T13:18:21.885Z [err] npm
2021-01-21T13:18:21.888Z [err]  WARN babel-loader@7.1.5 requires a peer of webpack@2 || 3 || 4 but none is installed. You must install peer dependencies yourself.
2021-01-21T13:18:21.891Z [err] npm
2021-01-21T13:18:21.891Z [err]  WARN
2021-01-21T13:18:21.891Z [err]  twilio@3.54.0 requires a peer of @types/qs@6.9.4 but none is installed. You must install peer dependencies yourself.
2021-01-21T13:18:21.892Z [err] 
2021-01-21T13:18:21.893Z [out] + node-red-contrib-animate-gif@1.0.9
2021-01-21T13:18:21.893Z [out] added 14 packages from 74 contributors in 17.247s
2021-01-21T13:18:21.919Z rc=0

Checking my mounted folder libvips was installed automatically, but some other things weren't:
![image](https://user-images.githubusercontent.com/51876074/105357173-b7478e80-5bf4-11eb-9cf4-e9b294e80bba.png)

Do you know what is the easiest way to do it (install missing dependencies in docker container not running as root)?

**Comment by i8beef** [comment]
Eww. What platform are you running CPU wise? I run on x86 in Docker and didn't have to install anything else, but I certainly don't intend to force everyone to install native dependencies either. If you really had to do this, I'd much rather dump sharp in favor of another processing library that isn't dependent on native libraries.

Short term you try installing the libvips package into your docker container as specified above. You'll lose it and have to redo it if you rebuild the container, but sounds like that will get you going. 

1. `docker exec -it <container name> /bin/bash`
2. `apk add vips-dev`
3. Ctrl-p, Ctrl-q to detach from the docker container

**Comment by cfullelove** [comment]
What version of the node-red docker image are you running? I'm running `nodered/node-red:1.2.6` on x86_64 and for whatever reason libvips wasn't installed by npm, and things only worked after adding the package through `apk`. I did install via the node-red front end, not npm on the cmd line, but I wouldn't have expected that to change anything.

Also, small note, I had to use `docker exec -it -u root <contained name> /bin/bash` as node-red runs as a non-root user that couldn't run `apk`.

**Comment by i8beef** [comment]
Im pretty much always on the latest, and I installed through the node-red interface too. The `npm install` behind the scenes looks like it downloads libvip binaries and sticks it in the node_modules folder which the sharp library uses directly... i.e., as long as you're running on an architecture that is supported by those binaries, it SHOULD just work, without installing an actual OS / container level copy. Worked for me that way anyway.

Regardless I'm exploring a few options here to just avoid the native dependency altogether.

**Comment by cfullelove** [comment]
You know what... now that I think about it I don't remember restarting node-red after installing the animate-gif package, meaning it wouldn't have picked up the library that got installed with npm. I did restart after installing the vips-dev package though, but it might not have been necessary after all.

**Comment by i8beef** [comment]
I just published a 2.0 version that will use a different underlying library. Give it a try.

**Comment by 111ar10** [comment]
Did not have much time last 2 days to test it out.
Wanted to try out other docker images.

But now installed version 2.0 and it works without any issues!!

Note that while installing still see this, and not sure how it influences anything:
2021-01-23T08:26:02.105Z Install : node-red-contrib-animate-gif 2.0.0

2021-01-23T08:26:01.605Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-animate-gif@2.0.0
2021-01-23T08:27:09.025Z [err] npm
2021-01-23T08:27:09.026Z [err]  WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
2021-01-23T08:27:09.033Z [err] npm WARN babel-loader@7.1.5 requires a peer of webpack@2 || 3 || 4 but none is installed. You must install peer dependencies yourself.
2021-01-23T08:27:09.035Z [err] npm
2021-01-23T08:27:09.035Z [err]  WARN twilio@3.54.0 requires a peer of @types/qs@6.9.4 but none is installed. You must install peer dependencies yourself.
2021-01-23T08:27:09.036Z [err] 
2021-01-23T08:27:09.037Z [out] + node-red-contrib-animate-gif@2.0.0
2021-01-23T08:27:09.037Z [out] added 63 packages from 38 contributors, removed 9 packages and updated 1 package in 66.647s
2021-01-23T08:27:09.071Z rc=0

In any case - works great for my use case.
I collect fixed number of images via camera API, combine them in buffer, then send to animate-gif node and finally send it to myself via telegram.

I think your node will provide very useful for home automation!
Thank you!!

**Comment by 111ar10** [comment]
Btw. running via docker-compose on intel NUC and nodered/node-red:1.2.7-10 image now.

  node-red:
    image: nodered/node-red:1.2.7-10       # use recommended node version 10 https://nodered.org/docs/faq/node-versions
    container_name: node-red
    restart: always
    user: '1102:1102'
    network_mode: host
    volumes:
      - /srv/docker/nodered/data:/data:rw
      - /srv/docker/nodered/bin:/usr/local/bin:rw
    environment:
      TZ: 'Europe/<city>'

Issue can be closed!

**Comment by i8beef** [comment]
Glad to hear the new version works for you without as much trouble. Closing out.
